---
apiVersion: v2
description: Squid HTTP Proxy
name: squid
version: 1.4.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: nold
    email: nold@gnu.one
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
